sapcc/octavia-f5-provider-driver

- octavia_f5/common/config.py
- octavia_f5/controller/statusmanager/status_manager.py
- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/restclient/as3restclient.py
- requirements.txt
PR for issue #14 
| metric | module | description |
|-|-|-|
| as3_httpstatus | as3restclient | Number of HTTP statuses in responses to AS3 requests |
| as3_post | as3restclient | Amount of POST requests sent to AS3 | 
| as3_post_time | as3restclient | Time it needs to send a POST request to AS3 | 
| as3_post_exceptions | as3restclient | Number of exceptions at POST requests sent to AS3 | 
| as3_patch | as3restclient | Amount of PATCH requests sent to AS3 | 
| as3_patch_time | as3restclient | Time it needs to send a PATCH request to AS3 | 
| as3_patch_exceptions | as3restclient | Number of exceptions at PATCH request sent to AS3 | 
| as3_delete | as3restclient | Amount of DELETE requests  sent to AS3 | 
| as3_delete_time | as3restclient | Time it needs to send a DELETE request to AS3 | 
| …
> Implement Prometheus metrics

- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/restclient/as3classes.py
- octavia_f5/restclient/as3objects/pool.py
- octavia_f5/restclient/as3objects/service.py
adds support for octavia backup member, will be realized
as custom service HTTP profile with fallback host.
Only one backup member supported.
fixes #37
> support for backup member

- octavia_f5/api/drivers/f5_driver/driver.py
- octavia_f5/common/config.py
- octavia_f5/controller/statusmanager/status_manager.py
- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/controller/worker/f5agent_driver.py
- octavia_f5/db/repositories.py
- octavia_f5/network/drivers/neutron/hierarchical_port_binding.py
- octavia_f5/network/drivers/noop_driver_f5/driver.py
- octavia_f5/restclient/as3restclient.py
- octavia_f5/tests/unit/api/__init__.py
- octavia_f5/tests/unit/api/drivers/__init__.py
- octavia_f5/tests/unit/api/drivers/f5_provider_driver/__init__.py
- octavia_f5/tests/unit/api/drivers/f5_provider_driver/test_f5_driver.py
- octavia_f5/tests/unit/controller/__init__.py
- octavia_f5/tests/unit/controller/worker/__init__.py
- octavia_f5/tests/unit/controller/worker/test_endpoint.py
loadbalancers will be automatically scheduled to the device with the lowest
amount of listeners.
(amphorae with loadbalancer_id == None and status == AMPHORAE_READY are
BigIP devices)
After scheduling, the agent creates an amphora binding with amphora.id ==
loadbalancer.id.
In case of failed scheduling, the reconciliation loop of any working agent
will pick up the pending loadbalancer and associate it.
fixes #4
> # added multi-agent and scheduling capability

- octavia_f5/controller/worker/f5agent_driver.py
- octavia_f5/restclient/as3classes.py
- octavia_f5/restclient/as3objects/irule.py
- octavia_f5/restclient/as3objects/pool.py
- octavia_f5/restclient/as3objects/service.py
Use tags in addition to special L7policy names to apply ESDs.
This PR belongs to #35.
L7policy-triggered ESDs are considered deprecated though and will be removed once all customers have migrated to tag-triggered ESDs.
> Map listener tags to Extended Service Definitions

- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/restclient/as3objects/certificate.py
- octavia_f5/restclient/as3objects/policy_endpoint.py
- octavia_f5/restclient/as3objects/pool.py
- octavia_f5/restclient/as3objects/pool_member.py
- octavia_f5/restclient/as3objects/service.py
- octavia_f5/restclient/as3objects/tls.py
- octavia_f5/restclient/as3restclient.py
- octavia_f5/restclient/as3types.py
- octavia_f5/utils/exceptions.py
depends on #46
This fixes following points:
* [BUGFIX] do not use duplicate certificates (else AS3 Error)
* [FEATURE] support inverted conditions
* [BUGFIX] fixed wrongly-spelled as3 compare types
* [BUGFIX] improve as3restclient debug logging in error case and throw exceptions
* [BUGFIX] catch as3 exceptions in reconciliation loop and skip update
> Multiple Fixes for as3, sanitation

- octavia_f5/controller/worker/controller_worker.py
also sets error correctly to all pending LBs since we cannot be sure
which of the lb's in the tenant caused the error. Although, this should
be no issue since there is no mass-update api of lb's so there should
be only one pending lb in the tenant.
> [controller_worker] avoid redundant syncs

- octavia_f5/controller/worker/controller_worker.py
There is no need to use futures when a clean separation of concerns does the job.
This PR
- makes `pending_sync` a small function that calls `schedule_lbs_to_worker` and `delete_load_balancer` separately
- introduces the two aforementioned functions, `schedule_lbs_to_worker` doing almost everything `pending_sync` did before, except deleting load balanceres which is now done by `delete_load_balancer`.
> Get rid of futures overhead by cleanly separating lock-annotated functions

- octavia_f5/common/config.py
- octavia_f5/controller/statusmanager/status_manager.py
- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/restclient/as3restclient.py
- octavia_f5/utils/exceptions.py
This adds failover functionality to `as3restclient` and
- makes it fail over when a F5 is not reachable
- makes the status manager fail over when the observed F5 is no longer in status `ACTIVE`
A few notes:
- Failover doesn't check whether the F5 that's being failed over to is actually in `ACTIVE` state. That functionality would imply traffic overhead.
- Currently more than two F5s aren't supported. That's because failover always selects the next F5 that is not currently selected, thus alternating between the first two F5s provided to the constructor.
AFAIK we don't use more than two F5s anywhere though, so I don't think that's a problem.
> Status manager failover

- octavia_f5/restclient/as3classes.py
- octavia_f5/restclient/as3objects/monitor.py
- octavia_f5/restclient/as3objects/pool.py
This was needed due to bugs in monitor creation with custom ip/port members.
Now, it's checked if all members have the same custom attributes so the amount
of monitors created can be reduced.
Also cleaner seperation of monitor-object creation
> [AS3] Rework monitor handling in case of custom monitor ports/ips

- octavia_f5/common/config.py
- octavia_f5/controller/worker/controller_worker.py
- octavia_f5/controller/worker/sync_manager.py
- octavia_f5/restclient/as3classes.py
this option disables:
* full reappearing sync of active devices
* failover to active devices
* sync_to_group (automatic device sync)
> Migration Mode: f5agent.migration allows only passive devices to sync

- octavia_f5/controller/worker/controller_worker.py
Since AS3 responses are to unreliable to detect a user-prone error.
Removing error-setting leads to (indefinitly) retrying of declarations.
Errors should be only set if an as3 response is clearly parsed and
identified as non-temporary.
fixes #100
> [controler_worker] remove provisioning_status = error for all entities

- octavia_f5/controller/worker/status_manager.py
- octavia_f5/restclient/as3objects/pool.py
- octavia_f5/restclient/as3objects/tenant.py
Since BigIP doesn't support chaining of loadbalancers, skip members
if the same ip-address is used in the same tenant as a load balancer
IP. Also sets the member provisioning_status = ERROR to give
feedback to user.
> [pool] Skip member if the IP is used by a VIP/Load-Balancer

- octavia_f5/restclient/as3objects/irule.py
- octavia_f5/restclient/as3objects/persist.py
- octavia_f5/restclient/as3objects/service.py
cookie method 'hash' seems to be buggy or wrongly configured,
use upstream method of iRule persistance instead.
> Replace APP_COOKIE persistance with universal persistance iRule

- octavia_f5/restclient/as3logging.py
- octavia_f5/restclient/as3restclient.py
This change unifies logging parsing in as3logging.py, and
extends task watcher for all AS3 request (like DELETE and PATCH) since
all AS3 requests could submit a task.
Also fixes the evaluation of task results (use as3 result 'code'
from json instead of http_code of the requests result)
> [as3restclient] Reworked as3 logging: Always log AS3 errors, catch retry

- octavia_f5/controller/worker/sync_manager.py
@notandy please don't merge yet
Instead of HTTP DELETE we POST an empty tenant declaration.
It works just as well, but additionally leaves us control over declaration persistency.
Also: Formatting
> Delete tenants by POSTing empty tenant declaration

- octavia_f5/common/constants.py
- octavia_f5/network/drivers/neutron/hierarchical_port_binding.py
Octavia-F5 is re-using the ports initially created by the lbaasv2-f5 driver
which have a different device_owner (network:f5lbaasv2). These ports should also
correctly cleaned up by Octavia.
> Also try to delete ports that are assigned to legacy lbaasv2 driver

- setup.cfg
This adds the provider 'F5Networks' as an alias for the octavia-f5
provider driver.
Why?
With switching to L7 neutron redirect, legacy clients could try to create new
loadbalancers with the old lbaasv2 provider name "F5Networks". The old proxy-driver
just stripped the provider completely.
> Added alias F5Networks for provider driver

- octavia_f5/controller/statusmanager/status_manager.py
The maximum allowed connections cannot be read via F5 metrics, but from the database. This incurs a small performance penalty.
This PR superseedes #134
> Calculate FULL listener status by database, since there is no F5 metric for it

- octavia_f5/restclient/as3objects/service.py
clientTLS on L4 listeners cause AS3 errors like `Cannot read property 'undefined' of undefined`
Also: Optimize imports
> Ignore L4-listener/TLS pool combination

- octavia_f5/restclient/as3types.py
- octavia_f5/tests/unit/restclient/test_as3types.py
Based on the regexes provided by upstream documentation, also includes tests
that check all conditions.
Fixes CCM-26032
> Correctly remove non-allowed characters in AS3 declaration for label+remark
